spring:
  datasource:
    url: jdbc:postgresql://postgres-services:5432/recommendation_db
    username: ${SERVICES_DB_USER}
    password: ${SERVICES_DB_PASSWORD}

  jpa:
    show-sql: false
  # Keycloak uses Docker service name
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/extroverted
          jwk-set-uri: http://keycloak:8080/realms/extroverted/protocol/openid-connect/certs

  data:
    redis:
      host: redis
      port: 6379

services:
  user-service:
    url: http://user-service:8083
  event-service:
    url: http://event-service:8084

logging:
  level:
    root: INFO
    com.event: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: WARN